# Render a per-site (per-gradient) markdown validation summary from
# all_sites_validated (validate_site() results, one row per site x check -
# see R/functions/pipeline/validate_site.R) and all_sites_cleaned (site ->
# list(meta, community, cover, taxa) - see R/site_plan.R), so at a glance you
# can see what's been checked for every gradient and what actually happened
# to its data (years covered, species/plots/rows), without opening the
# targets store.

#' @param all_sites_cleaned Named list, one element per site_id, each
#'   list(meta, community, cover, taxa) - the `all_sites_cleaned` target.
#' @param all_sites_validated Tibble with columns site, check, status,
#'   message - the `all_sites_validated` target.
#' @param out_path Path to write the markdown report to.
render_validation_report <- function(all_sites_cleaned, all_sites_validated,
                                      out_path = "docs/validation_report.md") {
  out_dir <- dirname(out_path)
  if (!dir.exists(out_dir)) dir.create(out_dir, recursive = TRUE)

  site_ids <- names(all_sites_cleaned)
  overview <- dplyr::bind_rows(lapply(site_ids, site_overview_row, all_sites_cleaned, all_sites_validated))
  overview <- overview[order(overview$site), ]

  n_fail_sites <- sum(overview$n_fail > 0)
  lines <- c(
    "# TransPlant Network - per-gradient validation summary",
    "",
    paste0(
      "Auto-generated by `render_validation_report()` (see ",
      "`R/functions/validation_report.R`) from the `all_sites_cleaned` and ",
      "`all_sites_validated` targets - do not edit by hand. Regenerate with ",
      "`targets::tar_make(validation_report)`."
    ),
    "",
    paste0(
      "**", length(site_ids), " sites checked, ", n_fail_sites,
      " with at least one failing check.** See `R/functions/pipeline/validate_site.R` ",
      "for what each check does."
    ),
    "",
    "## Overview",
    "",
    render_overview_table(overview),
    "",
    "## Per-site detail",
    "",
    unlist(lapply(overview$site, render_site_detail, all_sites_validated))
  )

  writeLines(lines, out_path)
  invisible(out_path)
}

#' One overview row for a single site: gradient/country/year metadata from
#' its meta table, a few size stats from its community table, and a rollup
#' of its validation check statuses.
site_overview_row <- function(site_id, all_sites_cleaned, all_sites_validated) {
  cleaned <- all_sites_cleaned[[site_id]]
  meta <- cleaned$meta
  comm <- cleaned$community
  checks <- all_sites_validated[all_sites_validated$site == site_id, ]

  tibble::tibble(
    site = site_id,
    gradient = if (!is.null(meta[["Gradient"]])) meta$Gradient[1] else NA_character_,
    country = if (!is.null(meta[["Country"]])) meta$Country[1] else NA_character_,
    year_min = if (!is.null(comm[["Year"]])) suppressWarnings(min(comm$Year, na.rm = TRUE)) else NA_integer_,
    year_max = if (!is.null(comm[["Year"]])) suppressWarnings(max(comm$Year, na.rm = TRUE)) else NA_integer_,
    n_species = if (!is.null(comm[["SpeciesName"]])) length(unique(comm$SpeciesName)) else NA_integer_,
    n_plots = if (!is.null(comm[["destPlotID"]])) length(unique(comm$destPlotID)) else NA_integer_,
    n_rows = nrow(comm),
    n_pass = sum(checks$status == "pass"),
    n_fail = sum(checks$status == "fail"),
    n_skip = sum(checks$status == "skip")
  )
}

status_emoji <- function(n_fail, n_skip) {
  if (n_fail > 0) "\u274c fail" else if (n_skip > 0) "\u26a0\ufe0f skip" else "\u2705 pass"
}

render_overview_table <- function(overview) {
  header <- c(
    "| Site | Gradient | Country | Years | Species | Plots | Rows | Checks (pass/fail/skip) | Status |",
    "|---|---|---|---|---|---|---|---|---|"
  )
  rows <- vapply(seq_len(nrow(overview)), function(i) {
    r <- overview[i, ]
    years <- if (is.finite(r$year_min) && is.finite(r$year_max)) paste0(r$year_min, "-", r$year_max) else "NA"
    paste0(
      "| `", r$site, "` | ", r$gradient %||% "", " | ", r$country %||% "", " | ", years, " | ",
      r$n_species, " | ", r$n_plots, " | ", r$n_rows, " | ",
      r$n_pass, "/", r$n_fail, "/", r$n_skip, " | ", status_emoji(r$n_fail, r$n_skip), " |"
    )
  }, character(1))
  paste(c(header, rows), collapse = "\n")
}

render_site_detail <- function(site_id, all_sites_validated) {
  checks <- all_sites_validated[all_sites_validated$site == site_id, ]
  n_fail <- sum(checks$status == "fail")
  n_skip <- sum(checks$status == "skip")

  header <- paste0("### `", site_id, "` ", status_emoji(n_fail, n_skip))
  table_header <- c(
    "| Check | Status | Message |",
    "|---|---|---|"
  )
  rows <- vapply(seq_len(nrow(checks)), function(i) {
    r <- checks[i, ]
    icon <- switch(r$status, pass = "\u2705", fail = "\u274c", skip = "\u26a0\ufe0f", "")
    paste0("| ", r$check, " | ", icon, " ", r$status, " | ", r$message, " |")
  }, character(1))

  c(header, "", table_header, rows, "")
}

`%||%` <- function(x, y) if (is.null(x)) y else x
